# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT       += core gui widgets
TEMPLATE = app
TARGET = CustomLikeBluePaintPro
DESTDIR = ./x64/Debug
CONFIG += debug
INCLUDEPATH += ./src/include
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(CustomLikeBluePaintPro.pri)
